import { createAuth } from "@pi-cast/db/auth-init"
import type { AuthConfig } from "@pi-cast/db/auth-init"
import {
  BETTER_AUTH_URL,
  BETTER_AUTH_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  WEB_CLIENT_URL,
} from "./constants"
import { ENV } from "varlock"

const authConfig: AuthConfig = {
  DATABASE_URL: ENV.DATABASE_URL,
  DATABASE_TOKEN: ENV.DATABASE_TOKEN,
  WEB_CLIENT_URL,
  BETTER_AUTH_URL,
  BETTER_AUTH_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  TRUSTED_ORIGINS: ENV.TRUSTED_ORIGINS,
  COOKIE_SECURE: ENV.COOKIE_SECURE,
  COOKIE_SAME_SITE: ENV.COOKIE_SAME_SITE ?? "lax",
  RATE_LIMIT_ENABLED: ENV.RATE_LIMIT_ENABLED,
  RATE_LIMIT_WINDOW_MS: Number(ENV.RATE_LIMIT_WINDOW_MS) || 60000,
  RATE_LIMIT_MAX_REQUESTS: Number(ENV.RATE_LIMIT_MAX_REQUESTS) || 100,
}

export const auth = createAuth(authConfig)
