/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiProfileUserUserIdFollowersParams,
  GetApiProfileUserUserIdFollowingParams,
  GetApiProfileUserUserIdLessonsParams,
  GetFollowersResponse,
  GetFollowingResponse,
  GetUserLessonsResponse,
  PublicProfile,
  RequestCreatorRole,
  RequestCreatorRoleResponse,
  ToggleFollow,
  ToggleFollowResponse,
  UpdateProfile,
  UpdateProfileError,
  UpdateProfileResponse,
  UserProfile
} from '.././schemas';

import { authFetch } from '../../orval/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the authenticated user's profile information
 * @summary Get current user profile
 */
export const getApiProfileMe = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<UserProfile>(
      {url: `/api/profile/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiProfileMeQueryKey = () => {
    return [
    `/api/profile/me`
    ] as const;
    }

    
export const getGetApiProfileMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiProfileMe>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileMe>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProfileMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProfileMe>>> = ({ signal }) => getApiProfileMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProfileMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiProfileMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProfileMe>>>
export type GetApiProfileMeQueryError = void


/**
 * @summary Get current user profile
 */

export function useGetApiProfileMe<TData = Awaited<ReturnType<typeof getApiProfileMe>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileMe>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiProfileMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update the authenticated user's profile information
 * @summary Update current user profile
 */
export const putApiProfileMe = (
    updateProfile: UpdateProfile,
 options?: SecondParameter<typeof authFetch>,) => {
      
      
      return authFetch<UpdateProfileResponse>(
      {url: `/api/profile/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProfile
    },
      options);
    }
  


export const getPutApiProfileMeMutationOptions = <TError = UpdateProfileError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProfileMe>>, TError,{data: UpdateProfile}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiProfileMe>>, TError,{data: UpdateProfile}, TContext> => {

const mutationKey = ['putApiProfileMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiProfileMe>>, {data: UpdateProfile}> = (props) => {
          const {data} = props ?? {};

          return  putApiProfileMe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiProfileMeMutationResult = NonNullable<Awaited<ReturnType<typeof putApiProfileMe>>>
    export type PutApiProfileMeMutationBody = UpdateProfile
    export type PutApiProfileMeMutationError = UpdateProfileError | void

    /**
 * @summary Update current user profile
 */
export const usePutApiProfileMe = <TError = UpdateProfileError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProfileMe>>, TError,{data: UpdateProfile}, TContext>, request?: SecondParameter<typeof authFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiProfileMe>>,
        TError,
        {data: UpdateProfile},
        TContext
      > => {

      const mutationOptions = getPutApiProfileMeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Request to upgrade to creator or teacher role
 * @summary Request creator role
 */
export const postApiProfileCreatorRole = (
    requestCreatorRole: RequestCreatorRole,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<RequestCreatorRoleResponse>(
      {url: `/api/profile/creator-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestCreatorRole, signal
    },
      options);
    }
  


export const getPostApiProfileCreatorRoleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProfileCreatorRole>>, TError,{data: RequestCreatorRole}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiProfileCreatorRole>>, TError,{data: RequestCreatorRole}, TContext> => {

const mutationKey = ['postApiProfileCreatorRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProfileCreatorRole>>, {data: RequestCreatorRole}> = (props) => {
          const {data} = props ?? {};

          return  postApiProfileCreatorRole(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiProfileCreatorRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProfileCreatorRole>>>
    export type PostApiProfileCreatorRoleMutationBody = RequestCreatorRole
    export type PostApiProfileCreatorRoleMutationError = void

    /**
 * @summary Request creator role
 */
export const usePostApiProfileCreatorRole = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProfileCreatorRole>>, TError,{data: RequestCreatorRole}, TContext>, request?: SecondParameter<typeof authFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiProfileCreatorRole>>,
        TError,
        {data: RequestCreatorRole},
        TContext
      > => {

      const mutationOptions = getPostApiProfileCreatorRoleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get a user's public profile by username
 * @summary Get public profile
 */
export const getApiProfileUsername = (
    username: string,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<PublicProfile>(
      {url: `/api/profile/${username}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiProfileUsernameQueryKey = (username?: string,) => {
    return [
    `/api/profile/${username}`
    ] as const;
    }

    
export const getGetApiProfileUsernameQueryOptions = <TData = Awaited<ReturnType<typeof getApiProfileUsername>>, TError = void>(username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUsername>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProfileUsernameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProfileUsername>>> = ({ signal }) => getApiProfileUsername(username, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUsername>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiProfileUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProfileUsername>>>
export type GetApiProfileUsernameQueryError = void


/**
 * @summary Get public profile
 */

export function useGetApiProfileUsername<TData = Awaited<ReturnType<typeof getApiProfileUsername>>, TError = void>(
 username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUsername>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiProfileUsernameQueryOptions(username,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get a user's published lessons with pagination
 * @summary Get user lessons
 */
export const getApiProfileUserUserIdLessons = (
    userId: string,
    params?: GetApiProfileUserUserIdLessonsParams,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<GetUserLessonsResponse>(
      {url: `/api/profile/user/${userId}/lessons`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiProfileUserUserIdLessonsQueryKey = (userId?: string,
    params?: GetApiProfileUserUserIdLessonsParams,) => {
    return [
    `/api/profile/user/${userId}/lessons`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiProfileUserUserIdLessonsQueryOptions = <TData = Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>, TError = unknown>(userId: string,
    params?: GetApiProfileUserUserIdLessonsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProfileUserUserIdLessonsQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>> = ({ signal }) => getApiProfileUserUserIdLessons(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiProfileUserUserIdLessonsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>>
export type GetApiProfileUserUserIdLessonsQueryError = unknown


/**
 * @summary Get user lessons
 */

export function useGetApiProfileUserUserIdLessons<TData = Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>, TError = unknown>(
 userId: string,
    params?: GetApiProfileUserUserIdLessonsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdLessons>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiProfileUserUserIdLessonsQueryOptions(userId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Follow or unfollow a user
 * @summary Toggle follow
 */
export const postApiProfileFollow = (
    toggleFollow: ToggleFollow,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<ToggleFollowResponse>(
      {url: `/api/profile/follow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: toggleFollow, signal
    },
      options);
    }
  


export const getPostApiProfileFollowMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProfileFollow>>, TError,{data: ToggleFollow}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiProfileFollow>>, TError,{data: ToggleFollow}, TContext> => {

const mutationKey = ['postApiProfileFollow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProfileFollow>>, {data: ToggleFollow}> = (props) => {
          const {data} = props ?? {};

          return  postApiProfileFollow(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiProfileFollowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProfileFollow>>>
    export type PostApiProfileFollowMutationBody = ToggleFollow
    export type PostApiProfileFollowMutationError = void

    /**
 * @summary Toggle follow
 */
export const usePostApiProfileFollow = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProfileFollow>>, TError,{data: ToggleFollow}, TContext>, request?: SecondParameter<typeof authFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiProfileFollow>>,
        TError,
        {data: ToggleFollow},
        TContext
      > => {

      const mutationOptions = getPostApiProfileFollowMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get a user's followers with pagination
 * @summary Get followers
 */
export const getApiProfileUserUserIdFollowers = (
    userId: string,
    params?: GetApiProfileUserUserIdFollowersParams,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<GetFollowersResponse>(
      {url: `/api/profile/user/${userId}/followers`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiProfileUserUserIdFollowersQueryKey = (userId?: string,
    params?: GetApiProfileUserUserIdFollowersParams,) => {
    return [
    `/api/profile/user/${userId}/followers`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiProfileUserUserIdFollowersQueryOptions = <TData = Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>, TError = unknown>(userId: string,
    params?: GetApiProfileUserUserIdFollowersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProfileUserUserIdFollowersQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>> = ({ signal }) => getApiProfileUserUserIdFollowers(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiProfileUserUserIdFollowersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>>
export type GetApiProfileUserUserIdFollowersQueryError = unknown


/**
 * @summary Get followers
 */

export function useGetApiProfileUserUserIdFollowers<TData = Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>, TError = unknown>(
 userId: string,
    params?: GetApiProfileUserUserIdFollowersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowers>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiProfileUserUserIdFollowersQueryOptions(userId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get users that a user is following with pagination
 * @summary Get following
 */
export const getApiProfileUserUserIdFollowing = (
    userId: string,
    params?: GetApiProfileUserUserIdFollowingParams,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<GetFollowingResponse>(
      {url: `/api/profile/user/${userId}/following`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiProfileUserUserIdFollowingQueryKey = (userId?: string,
    params?: GetApiProfileUserUserIdFollowingParams,) => {
    return [
    `/api/profile/user/${userId}/following`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiProfileUserUserIdFollowingQueryOptions = <TData = Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>, TError = unknown>(userId: string,
    params?: GetApiProfileUserUserIdFollowingParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProfileUserUserIdFollowingQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>> = ({ signal }) => getApiProfileUserUserIdFollowing(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiProfileUserUserIdFollowingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>>
export type GetApiProfileUserUserIdFollowingQueryError = unknown


/**
 * @summary Get following
 */

export function useGetApiProfileUserUserIdFollowing<TData = Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>, TError = unknown>(
 userId: string,
    params?: GetApiProfileUserUserIdFollowingParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiProfileUserUserIdFollowing>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiProfileUserUserIdFollowingQueryOptions(userId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




