/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export interface AdminUser {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image: string | null;
  /** @nullable */
  role: string | null;
  createdAt: number;
}
