/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export interface Follower {
  userId: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  bio: string | null;
  /** @nullable */
  location: string | null;
  /** @nullable */
  website: string | null;
  /** @nullable */
  followersCount: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  followingCount: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  lessonsCount: number;
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  isFollowing: boolean;
}
