/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProfileUserUserIdLessonsParams = {
/**
 * @nullable
 */
page?: number | null;
/**
 * @nullable
 */
limit?: number | null;
};
