/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import type { Follower } from './follower';
import type { Pagination } from './pagination';

export interface GetFollowersResponse {
  followers: Follower[];
  pagination: Pagination;
}
