/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import type { Lesson } from './lesson';
import type { Pagination } from './pagination';

export interface GetUserLessonsResponse {
  lessons: Lesson[];
  pagination: Pagination;
}
