/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUser } from './adminUser';
import type { AdminPagination } from './adminPagination';

export interface GetUsersResponse {
  users: AdminUser[];
  pagination: AdminPagination;
}
