/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Get the authenticated user's profile information
 * @summary Get current user profile
 */
export const getApiProfileMeResponse = zod.object({
  "userId": zod.string().describe('User ID'),
  "username": zod.string().nullable().describe('Username'),
  "bio": zod.string().nullable().describe('User bio'),
  "location": zod.string().nullable().describe('Location'),
  "website": zod.string().nullable().describe('Website URL'),
  "followersCount": zod.number().describe('Number of followers'),
  "followingCount": zod.number().describe('Number of following'),
  "lessonsCount": zod.number().describe('Number of lessons'),
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.email(),
  "emailVerified": zod.boolean(),
  "image": zod.string().nullable(),
  "role": zod.string().nullable()
})


/**
 * Update the authenticated user's profile information
 * @summary Update current user profile
 */
export const putApiProfileMeBodyUsernameMin = 3;
export const putApiProfileMeBodyUsernameMax = 30;

export const putApiProfileMeBodyBioMax = 500;



export const putApiProfileMeBody = zod.strictObject({
  "name": zod.string().optional(),
  "username": zod.string().min(putApiProfileMeBodyUsernameMin).max(putApiProfileMeBodyUsernameMax).optional(),
  "bio": zod.string().max(putApiProfileMeBodyBioMax).optional(),
  "location": zod.string().optional(),
  "website": zod.string().optional(),
  "image": zod.url().optional()
})

export const putApiProfileMeResponseDataUsernameMin = 3;
export const putApiProfileMeResponseDataUsernameMax = 30;

export const putApiProfileMeResponseDataBioMax = 500;



export const putApiProfileMeResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "data": zod.object({
  "name": zod.string().optional(),
  "username": zod.string().min(putApiProfileMeResponseDataUsernameMin).max(putApiProfileMeResponseDataUsernameMax).optional(),
  "bio": zod.string().max(putApiProfileMeResponseDataBioMax).optional(),
  "location": zod.string().optional(),
  "website": zod.string().optional(),
  "image": zod.url().optional()
})
})


/**
 * Request to upgrade to creator or teacher role
 * @summary Request creator role
 */
export const postApiProfileCreatorRoleBody = zod.strictObject({
  "roleType": zod.enum(['creator', 'teacher']).optional()
})

export const postApiProfileCreatorRoleResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "role": zod.string()
})


/**
 * Get a user's public profile by username
 * @summary Get public profile
 */
export const getApiProfileUsernameParams = zod.object({
  "username": zod.string()
})

export const getApiProfileUsernameResponse = zod.object({
  "user": zod.object({
  "userId": zod.string(),
  "username": zod.string().nullable(),
  "bio": zod.string().nullable(),
  "location": zod.string().nullable(),
  "website": zod.string().nullable(),
  "followersCount": zod.number(),
  "followingCount": zod.number(),
  "lessonsCount": zod.number(),
  "id": zod.string(),
  "name": zod.string(),
  "image": zod.string().nullable(),
  "role": zod.string().nullable(),
  "createdAt": zod.number(),
  "stats": zod.object({
  "followers": zod.number(),
  "following": zod.number(),
  "lessons": zod.number()
})
}),
  "lessons": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "thumbnailUrl": zod.string().nullable(),
  "level": zod.string().nullable(),
  "viewCount": zod.number(),
  "likeCount": zod.number(),
  "duration": zod.number().nullable(),
  "createdAt": zod.number()
})),
  "isFollowing": zod.boolean(),
  "isFollowedByCurrentUser": zod.boolean()
})


/**
 * Get a user's published lessons with pagination
 * @summary Get user lessons
 */
export const getApiProfileUserUserIdLessonsParams = zod.object({
  "userId": zod.string()
})

export const getApiProfileUserUserIdLessonsQueryPageDefault = 1;export const getApiProfileUserUserIdLessonsQueryLimitDefault = 20;

export const getApiProfileUserUserIdLessonsQueryParams = zod.object({
  "page": zod.number().default(getApiProfileUserUserIdLessonsQueryPageDefault),
  "limit": zod.number().default(getApiProfileUserUserIdLessonsQueryLimitDefault)
})

export const getApiProfileUserUserIdLessonsResponse = zod.object({
  "lessons": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "thumbnailUrl": zod.string().nullable(),
  "level": zod.string().nullable(),
  "viewCount": zod.number(),
  "likeCount": zod.number(),
  "duration": zod.number().nullable(),
  "createdAt": zod.number()
})),
  "pagination": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * Follow or unfollow a user
 * @summary Toggle follow
 */
export const postApiProfileFollowBody = zod.strictObject({
  "userId": zod.string()
})

export const postApiProfileFollowResponse = zod.object({
  "success": zod.boolean(),
  "following": zod.boolean()
})


/**
 * Get a user's followers with pagination
 * @summary Get followers
 */
export const getApiProfileUserUserIdFollowersParams = zod.object({
  "userId": zod.string()
})

export const getApiProfileUserUserIdFollowersQueryPageDefault = 1;export const getApiProfileUserUserIdFollowersQueryLimitDefault = 20;

export const getApiProfileUserUserIdFollowersQueryParams = zod.object({
  "page": zod.number().default(getApiProfileUserUserIdFollowersQueryPageDefault),
  "limit": zod.number().default(getApiProfileUserUserIdFollowersQueryLimitDefault)
})

export const getApiProfileUserUserIdFollowersResponseFollowersItemFollowingCountMin = -9007199254740991;
export const getApiProfileUserUserIdFollowersResponseFollowersItemFollowingCountMax = 9007199254740991;

export const getApiProfileUserUserIdFollowersResponseFollowersItemLessonsCountMin = -9007199254740991;
export const getApiProfileUserUserIdFollowersResponseFollowersItemLessonsCountMax = 9007199254740991;



export const getApiProfileUserUserIdFollowersResponse = zod.object({
  "followers": zod.array(zod.object({
  "userId": zod.string(),
  "username": zod.string().nullable(),
  "bio": zod.string().nullable(),
  "location": zod.string().nullable(),
  "website": zod.string().nullable(),
  "followersCount": zod.number().nullable(),
  "followingCount": zod.number().min(getApiProfileUserUserIdFollowersResponseFollowersItemFollowingCountMin).max(getApiProfileUserUserIdFollowersResponseFollowersItemFollowingCountMax),
  "lessonsCount": zod.number().min(getApiProfileUserUserIdFollowersResponseFollowersItemLessonsCountMin).max(getApiProfileUserUserIdFollowersResponseFollowersItemLessonsCountMax),
  "id": zod.string(),
  "name": zod.string(),
  "image": zod.string().nullable(),
  "isFollowing": zod.boolean()
})),
  "pagination": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * Get users that a user is following with pagination
 * @summary Get following
 */
export const getApiProfileUserUserIdFollowingParams = zod.object({
  "userId": zod.string()
})

export const getApiProfileUserUserIdFollowingQueryPageDefault = 1;export const getApiProfileUserUserIdFollowingQueryLimitDefault = 20;

export const getApiProfileUserUserIdFollowingQueryParams = zod.object({
  "page": zod.number().default(getApiProfileUserUserIdFollowingQueryPageDefault),
  "limit": zod.number().default(getApiProfileUserUserIdFollowingQueryLimitDefault)
})

export const getApiProfileUserUserIdFollowingResponseFollowingItemFollowingCountMin = -9007199254740991;
export const getApiProfileUserUserIdFollowingResponseFollowingItemFollowingCountMax = 9007199254740991;

export const getApiProfileUserUserIdFollowingResponseFollowingItemLessonsCountMin = -9007199254740991;
export const getApiProfileUserUserIdFollowingResponseFollowingItemLessonsCountMax = 9007199254740991;



export const getApiProfileUserUserIdFollowingResponse = zod.object({
  "following": zod.array(zod.object({
  "userId": zod.string(),
  "username": zod.string().nullable(),
  "bio": zod.string().nullable(),
  "location": zod.string().nullable(),
  "website": zod.string().nullable(),
  "followersCount": zod.number().nullable(),
  "followingCount": zod.number().min(getApiProfileUserUserIdFollowingResponseFollowingItemFollowingCountMin).max(getApiProfileUserUserIdFollowingResponseFollowingItemFollowingCountMax),
  "lessonsCount": zod.number().min(getApiProfileUserUserIdFollowingResponseFollowingItemLessonsCountMin).max(getApiProfileUserUserIdFollowingResponseFollowingItemLessonsCountMax),
  "id": zod.string(),
  "name": zod.string(),
  "image": zod.string().nullable(),
  "isFollowing": zod.boolean()
})),
  "pagination": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * Get all users (admin only)
 * @summary Get all users
 */
export const getApiAdminUsersQueryPageDefault = 1;export const getApiAdminUsersQueryLimitDefault = 20;

export const getApiAdminUsersQueryParams = zod.object({
  "page": zod.number().default(getApiAdminUsersQueryPageDefault),
  "limit": zod.number().default(getApiAdminUsersQueryLimitDefault)
})

export const getApiAdminUsersResponse = zod.object({
  "users": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.email(),
  "emailVerified": zod.boolean(),
  "image": zod.string().nullable(),
  "role": zod.string().nullable(),
  "createdAt": zod.number()
})),
  "pagination": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * Get platform statistics (admin only)
 * @summary Get platform stats
 */
export const getApiAdminStatsResponse = zod.object({
  "totalUsers": zod.number(),
  "totalLessons": zod.number(),
  "totalOrganizations": zod.number()
})


