/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export interface RequestCreatorRoleResponse {
  success: boolean;
  message: string;
  role: string;
}
