/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProfile {
  name?: string;
  /**
   * @minLength 3
   * @maxLength 30
   */
  username?: string;
  /** @maxLength 500 */
  bio?: string;
  location?: string;
  website?: string;
  image?: string;
}
