/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfileErrorError } from './updateProfileErrorError';

export interface UpdateProfileError {
  success: boolean;
  error: UpdateProfileErrorError;
}
