/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */

export interface UserProfile {
  /** User ID */
  userId: string;
  /**
   * Username
   * @nullable
   */
  username: string | null;
  /**
   * User bio
   * @nullable
   */
  bio: string | null;
  /**
   * Location
   * @nullable
   */
  location: string | null;
  /**
   * Website URL
   * @nullable
   */
  website: string | null;
  /** Number of followers */
  followersCount: number;
  /** Number of following */
  followingCount: number;
  /** Number of lessons */
  lessonsCount: number;
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image: string | null;
  /** @nullable */
  role: string | null;
}
