/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import type { UserStats } from './userStats';

export interface UserPublic {
  userId: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  bio: string | null;
  /** @nullable */
  location: string | null;
  /** @nullable */
  website: string | null;
  followersCount: number;
  followingCount: number;
  lessonsCount: number;
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  role: string | null;
  createdAt: number;
  stats: UserStats;
}
