/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminStats,
  GetApiAdminUsersParams,
  GetUsersResponse
} from '.././schemas';

import { authFetch } from '../../orval/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all users (admin only)
 * @summary Get all users
 */
export const getApiAdminUsers = (
    params?: GetApiAdminUsersParams,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<GetUsersResponse>(
      {url: `/api/admin/users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAdminUsersQueryKey = (params?: GetApiAdminUsersParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(params?: GetApiAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminUsers>>> = ({ signal }) => getApiAdminUsers(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> } // eslint-disable-line @typescript-eslint/consistent-type-assertions
}

export type GetApiAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminUsers>>>
export type GetApiAdminUsersQueryError = void


export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params: undefined |  GetApiAdminUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params?: GetApiAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params?: GetApiAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all users
 */

export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params?: GetApiAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient);

  return query as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }; // eslint-disable-line @typescript-eslint/consistent-type-assertions
}




/**
 * Get platform statistics (admin only)
 * @summary Get platform stats
 */
export const getApiAdminStats = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<AdminStats>(
      {url: `/api/admin/stats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAdminStatsQueryKey = () => {
    return [
    `/api/admin/stats`
    ] as const;
    }

    
export const getGetApiAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminStats>>> = ({ signal }) => getApiAdminStats(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> } // eslint-disable-line @typescript-eslint/consistent-type-assertions
}

export type GetApiAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminStats>>>
export type GetApiAdminStatsQueryError = void


export function useGetApiAdminStats<TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminStats<TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminStats<TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get platform stats
 */

export function useGetApiAdminStats<TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient);

  return query as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }; // eslint-disable-line @typescript-eslint/consistent-type-assertions
}




