/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Pi-Cast API
 * Pi-Cast API documentation with Better Auth integration
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminStats,
  GetApiAdminUsersParams,
  GetUsersResponse
} from '.././schemas';

import { authFetch } from '../../orval/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all users (admin only)
 * @summary Get all users
 */
export const getApiAdminUsers = (
    params?: GetApiAdminUsersParams,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<GetUsersResponse>(
      {url: `/api/admin/users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAdminUsersQueryKey = (params?: GetApiAdminUsersParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(params?: GetApiAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminUsers>>> = ({ signal }) => getApiAdminUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminUsers>>>
export type GetApiAdminUsersQueryError = void


/**
 * @summary Get all users
 */

export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params?: GetApiAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get platform statistics (admin only)
 * @summary Get platform stats
 */
export const getApiAdminStats = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<AdminStats>(
      {url: `/api/admin/stats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAdminStatsQueryKey = () => {
    return [
    `/api/admin/stats`
    ] as const;
    }

    
export const getGetApiAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminStats>>> = ({ signal }) => getApiAdminStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminStats>>>
export type GetApiAdminStatsQueryError = void


/**
 * @summary Get platform stats
 */

export function useGetApiAdminStats<TData = Awaited<ReturnType<typeof getApiAdminStats>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminStats>>, TError, TData>, request?: SecondParameter<typeof authFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




